name: Unit test and build

on:
  workflow_dispatch:

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GO SDK
        uses: actions/setup-go@v3
        with:
          check-latest: true
          cache: true

      - name: Run unit test
        run: go test -json ./internal/...
